name: Deploy Slides

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert Markdown to HTML (Multi-project)
        run: |
          mkdir dist
          
          for dir in project-*; do
            if [ -d "$dir" ]; then
              echo "Processing $dir..."
              mkdir -p "dist/$dir"
              npx @marp-team/marp-cli@latest "$dir/presentation.md" -o "dist/$dir/index.html" --theme-set style.css
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages